

# dynamic reconfigure parameters
exposure: 2000
gain: 0.0
max_framerate: 10
balance_ratio: 1.0


# image processing parameters
jpeg_quality: 96
resize_width: 3072.0

tone_mapping: reinhard

# rotate_90 rotate_180 rotate_270 transpose flip_horiz flip_vert transverse
transform: rotate_270
auto_start: True


camera_settings:
  device:
    - UserSetSelector: Default
    - PixelFormat: BayerRG12p

    # Turn all the auto off
    - ExposureAuto: "Off"
    - GainAuto: "Off"
    - BalanceWhiteAuto: "Off"
    - BlackLevel: 0
    - BlackLevelClampingEnable: False
    - GammaEnable: False
    # - TriggerDelay: 29.0 # Microseconds

    - ChunkModeActive: True
    - ChunkSelector: "Timestamp"
    - ChunkEnable: True
    - ChunkSelector: "FrameID"
    - ChunkEnable: True

  transport_layer:
    - StreamBufferCountMode: Manual
    - StreamBufferCountManual: 2
    - StreamBufferHandlingMode: OldestFirst

