cameras:
  cam1: 19280415
  cam2: 19195147
  cam3: 19194310
  cam4: 19194309
  cam5: 19340241
  cam6: 19340240

master: cam1


reset_cycle: true
device: cuda:0

sync_threshold_msec: 20   # threshold to consider images from the same trigger
timeout_msec: 1000       # timeout for images waiting to be matched up with a trigger

transform: rotate_90
