cameras:
  cam1: 22580855
  cam2: 22580857
  cam3: 22395934
  cam4: 22580858
  cam5: 22395939
  cam6: 22395922

master: cam6

reset_cycle: true
device: cuda:0

sync_threshold_msec: 10   # threshold to consider images from the same trigger
timeout_msec: 500        # timeout for images waiting to be matched up with a trigger

transform: rotate_90
